//! # ForgePass Shared Contract Types
//!
//! Single source of truth for all `#[contracttype]` structs, enums, and the
//! `ContractError` enum shared across all four ForgePass Soroban contracts.
//!
//! **ABI authority:** `contracts/INTERFACES.md` (Issue #014, complete)
//!
//! Import this crate in each contract crate's `Cargo.toml`:
//! ```toml
//! forgepass-shared = { path = "../shared" }
//! ```
//!
//! Do **not** add fields or variants without a corresponding update to
//! `INTERFACES.md` and a coordinated WASM upgrade across all four contracts.

#![no_std]

use soroban_sdk::{contracterror, contracttype, Address, BytesN, String};

// =============================================================================
// Structs
// =============================================================================

/// On-chain passport record. One per contributor, keyed by wallet `Address`.
///
/// Stored in **persistent** storage in the passport contract so it survives
/// ledger entry TTL expiry (FR-02.3 non-revocability). TTL extension is a
/// backend concern handled by the `OnchainWriterService` (issue #027).
///
/// ABI: `INTERFACES.md` Section 3.1
#[contracttype]
#[derive(Clone)]
pub struct PassportRecord {
    /// Stellar public key. Primary key for this passport record.
    pub wallet: Address,
    /// CIDv1 of the IPFS/Arweave metadata object. Non-empty; max 100 chars.
    /// Raw PII is **never** stored on-chain -- only the content-addressed hash
    /// (FR-02.5). The `StorageService` in issue #044 handles the off-chain pin.
    pub ipfs_cid: String,
    /// Unix timestamp (seconds) of passport creation.
    /// Always sourced from `env.ledger().timestamp()` inside the contract --
    /// never from a caller-supplied argument (prevents backdating).
    pub created_at: u64,
    /// Admin-set sybil flag. Default: `false`.
    /// Toggled only via `set_sybil_flag`. A flagged passport remains on-chain
    /// (FR-02.3); the API layer applies the read exclusion (FR-11.1).
    pub sybil_flagged: bool,
}

/// On-chain credential proof anchoring a contribution signal to a passport.
///
/// Stored in **persistent** storage in the credential-store contract.
/// Live credentials (up to 100 per wallet) are stored as a
/// `Vec<CredentialRecord>` under `DataKey::Credentials(wallet)`.
/// Archived credentials are removed via `remove_credentials` and replaced by
/// an `ArchiveRecord` Merkle root.
///
/// ABI: `INTERFACES.md` Section 3.2
#[contracttype]
#[derive(Clone)]
pub struct CredentialRecord {
    /// Contract-generated monotonic ID. Never reuses IDs, even after archival.
    /// Generated by a per-wallet counter in instance storage.
    pub id: u64,
    /// FK to `PassportRecord.wallet`.
    pub wallet: Address,
    /// Contribution signal type. v1 active variants only (reserved variants
    /// are defined in `SignalType` and are appended via WASM upgrade).
    pub signal_type: SignalType,
    /// External reference ID paired with `signal_type` as the deduplication key.
    /// `(signal_type, source_id)` must be unique in the live credential set.
    pub source_id: String,
    /// Unix timestamp (seconds) of the original contribution event.
    pub event_date: u64,
    /// SHA-256 hex string of the raw signal data. Always 64 chars.
    pub data_hash: String,
}

/// Versioned Trust Score snapshot, anchored on-chain after each recalculation.
///
/// Stored in **persistent** storage as a bounded `Vec<ScoreSnapshot>` (max 50)
/// per wallet under `DataKey::ScoreHistory(wallet)` in the trust-score contract.
/// The latest snapshot is also mirrored to instance storage under
/// `DataKey::CurrentScore(wallet)` for O(1) reads.
///
/// ABI: `INTERFACES.md` Section 3.3
#[contracttype]
#[derive(Clone)]
pub struct ScoreSnapshot {
    /// Trust Score value. Always in range [0, 100].
    /// `anchor_score` rejects values outside this range with `InvalidScore` (400).
    pub score: u32,
    /// Semver string of the scoring algorithm, e.g. `"1.0"`.
    pub algorithm_version: String,
    /// SHA-256 hex string of the input signal set used for this computation.
    pub signal_hash: String,
    /// Unix timestamp (seconds) of when the score was computed off-chain.
    pub computed_at: u64,
}

/// Soulbound achievement badge NFT record. Non-transferable by design.
///
/// At most one `BadgeRecord` per `(wallet, MilestoneType)` pair.
/// Stored in **persistent** storage in the soulbound-nft contract under
/// `DataKey::Badge(badge_id)`.
///
/// ABI: `INTERFACES.md` Section 3.4
#[contracttype]
#[derive(Clone)]
pub struct BadgeRecord {
    /// Contract-generated **global** monotonic ID across all wallets.
    /// Never reused. Starts at 1, increments on every successful `mint`.
    pub badge_id: u64,
    /// Badge holder wallet address.
    pub wallet: Address,
    /// Milestone type. At most one `BadgeRecord` per `(wallet, MilestoneType)` pair.
    pub milestone_type: MilestoneType,
    /// CID of the badge metadata JSON on IPFS/Arweave.
    pub ipfs_cid: String,
    /// Unix timestamp (seconds) of the `mint` call.
    pub minted_at: u64,
}

/// On-chain Merkle root proof anchored after each credential archival cycle.
///
/// Stored in **persistent** storage in the credential-store contract.
/// One entry per archival cycle per wallet, keyed by
/// `DataKey::ArchiveRecord(wallet, archive_index)`.
/// `archive_index` is a monotonically increasing `u32` per wallet, starting at 0,
/// managed in instance storage under `DataKey::ArchiveIndex(wallet)`.
///
/// Full archival workflow: `contracts/ARCHITECTURE.md` Section 4.
///
/// ABI: `INTERFACES.md` Section 3.5
#[contracttype]
#[derive(Clone)]
pub struct ArchiveRecord {
    /// 32-byte SHA-256 Merkle root of the archived credential batch.
    /// Must match the `merkle_root` field in the IPFS archive JSON file.
    pub merkle_root: BytesN<32>,
    /// Number of credentials in this specific archive batch.
    pub credential_count: u32,
    /// Unix timestamp (seconds) of when `add_archive_record` was called.
    pub archived_at: u64,
    /// CID of the archive JSON on IPFS/Arweave.
    /// Stored on-chain so third parties can verify without querying ForgePass API.
    pub ipfs_cid: String,
}

// =============================================================================
// Enums
// =============================================================================

/// Contribution signal source types.
///
/// **v1 active:** `GithubPr`, `SorobanContract`, `StellarDex`, `Hackathon`.
/// **Reserved:** `ScfGrant`, `GrantfoxBounty`, `TrustlessWork` -- appended via
/// WASM upgrade when the corresponding partnership is confirmed (issue #009).
///
/// **Contracts never branch on `SignalType` in function bodies.** All signal-
/// type-specific logic lives in the NestJS scoring engine (off-chain). New
/// variants can be appended without any credential-store contract logic change.
///
/// ABI: `INTERFACES.md` Section 3.6
#[contracttype]
#[derive(Clone)]
pub enum SignalType {
    /// GitHub pull requests merged into admin-registered Stellar ecosystem repos.
    GithubPr,
    /// Soroban smart contract deployments from the contributor's wallet.
    SorobanContract,
    /// DEX trades and Aquarius LP positions via Stellar Horizon.
    StellarDex,
    /// Hackathon participation records ingested via admin batch upload.
    Hackathon,
    // --- Reserved: no v1 contract logic. Activated via WASM upgrade once the
    // --- corresponding partnership is confirmed via issue #009 (FR-09-B).
    /// Reserved: SCF grant history. Gated on #009 confirmation + issue R07.
    ScfGrant,
    /// Reserved: GrantFox bounty completions. Gated on #009 confirmation + R05.
    GrantfoxBounty,
    /// Reserved: Trustless Work milestone completions. Gated on #009 + R06.
    TrustlessWork,
}

/// Achievement badge milestone types.
///
/// **v1 active (7):** `FirstPr`, `FirstContract`, `HackathonParticipant`,
/// `RisingContributor`, `MultiRepoContributor`, `FirstSorobanInvocation`,
/// `FullStackBuilder`.
/// **Reserved (3):** `FirstBounty`, `FirstGrant`, `FirstTrustlessWork`.
/// Trigger criteria: `contracts/badges/milestone-registry.json` (issue #008).
///
/// **The soulbound-nft contract never branches on `MilestoneType` in function
/// bodies.** New variants can be appended via WASM upgrade without logic changes.
///
/// ABI: `INTERFACES.md` Section 3.7
#[contracttype]
#[derive(Clone)]
pub enum MilestoneType {
    /// First merged PR (author) into a registered Stellar ecosystem repo.
    FirstPr,
    /// First Soroban contract deployed by the contributor's wallet.
    FirstContract,
    /// Verified participation in an admin-registered Stellar hackathon event.
    HackathonParticipant,
    /// 10+ merged PRs (author) across registered Stellar repos. Compound badge.
    RisingContributor,
    /// Merged PRs across 3+ distinct registered Stellar repos. Compound badge.
    MultiRepoContributor,
    /// First invocation of any contract deployed by the wallet (any caller).
    FirstSorobanInvocation,
    /// At least 1 `GithubPr` credential AND 1 `SorobanContract` credential.
    FullStackBuilder,
    // --- Reserved: no v1 contract logic. Activated via WASM upgrade when the
    // --- corresponding signal source is confirmed and live.
    /// Reserved: first GrantFox bounty. Gated on #009 confirmation + R05.
    FirstBounty,
    /// Reserved: first SCF grant. Gated on #009 confirmation + R07.
    FirstGrant,
    /// Reserved: first Trustless Work milestone. Gated on #009 confirmation + R06.
    FirstTrustlessWork,
}

// =============================================================================
// Error enum
// =============================================================================

/// Unified error enum for all four ForgePass Soroban contracts.
///
/// Discriminants are grouped by hundreds so the originating contract is
/// identifiable from error codes in NestJS logs and Horizon transaction results.
///
/// **Auth failure model:** auth failures on admin-only and owner-only functions
/// are Soroban **host traps** (`INVOKE_HOST_FUNCTION_TRAPPED`), NOT
/// `ContractError` returns. `require_auth()` in SDK `22.0.11` traps on failure.
/// `Unauthorized` (102) is a semantic marker reserved for future use -- no v1
/// function returns it.
///
/// ABI: `INTERFACES.md` Section 3.8
#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ContractError {
    // 100s -- Initialisation (all four contracts)
    /// `initialize` called a second time. Admin address is unchanged.
    AlreadyInitialized = 100,
    /// Admin-only function called before `initialize` has stored the admin address.
    NotInitialized = 101,
    /// Semantic marker. No v1 function returns this -- auth failures are host traps.
    Unauthorized = 102,

    // 200s -- Passport contract
    /// `update_metadata_cid` or `set_sybil_flag`: no passport exists for this wallet.
    PassportNotFound = 200,
    /// `create_passport`: wallet already has a passport. Idempotency-safe return --
    /// the original record is unchanged; this is not a panic.
    PassportAlreadyExists = 201,

    // 300s -- Credential store contract
    /// `add_credential`: `(signal_type, source_id)` pair already exists in live set.
    CredentialAlreadyExists = 300,
    /// Reserved. No v1 function returns this variant.
    CredentialNotFound = 301,
    /// `remove_credentials`: called before `add_archive_record` -- prevents
    /// credential deletion without a corresponding on-chain Merkle root proof.
    ArchiveRecordRequired = 302,

    // 400s -- Trust Score contract
    /// `anchor_score`: score value is outside the valid 0-100 range.
    InvalidScore = 400,
    /// `anchor_score` defensive guard: snapshot count exceeded 50 before cap
    /// management ran. Indicates a backend implementation bug, not a user error.
    HistoryCapExceeded = 401,

    // 500s -- Soulbound NFT contract
    /// `mint`: wallet already holds a badge for this `MilestoneType`.
    BadgeAlreadyMinted = 500,
    /// Reserved. `get_badge` returns `Option<BadgeRecord>` -- not this error.
    BadgeNotFound = 501,
    /// **Test harness only.** No transfer function exists in the soulbound-nft
    /// contract. This variant provides a runtime-verifiable proof of
    /// non-transferability alongside the interface-level proof.
    TransferNotAllowed = 502,
}
